# Generated by Django 2.2.3 on 2019-07-22 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('no_tel', models.CharField(max_length=16)),
                ('bidang', models.CharField(max_length=255)),
                ('jadwal_praktek', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('khasiat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('no_tel', models.CharField(max_length=16)),
                ('alamat', models.TextField()),
                ('keluhan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('total_harga', models.IntegerField()),
                ('kumpulan_obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rumahsakit.Obat')),
            ],
        ),
    ]
