# Generated by Django 2.2.3 on 2019-07-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumahsakit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resep',
            name='kumpulan_obat',
            field=models.TextField(),
        ),
    ]
